.github/workflows/rust.yml

Use Rust toolchains with working components.

---

.github/workflows/rust.yml

Split licenses check into a separate test target.

---

CHANGELOG.md
Cargo.toml
cargo/Cargo.lock

Release v0.1.2.

---

Cargo.toml
cargo/BUILD
cargo/Cargo.lock
cargo/crates.bzl
cargo/remote/hashbrown-0.8.2.BUILD

Update hashbrown to v0.8.2.

---

.github/workflows/rust.yml

Add cargo audit and cargo outdated checks.

---

cargo/BUILD
cargo/Cargo.lock
cargo/crates.bzl
cargo/remote/chrono-0.4.15.BUILD

Update chrono to v0.4.15.

---

src/traits.rs

Add support for setting network buffers.

---

WORKSPACE

Update rules_rust to latest.

---

.github/workflows/rust.yml
Cargo.toml
bazel/cargo/remote/BUILD.getrandom-0.2.0.bazel
bazel/cargo/remote/BUILD.libc-0.2.80.bazel
bazel/cargo/remote/BUILD.log-0.4.11.bazel

Use cargo-raze's gen_buildrs for trusted crates.

---

src/dispatcher.rs

Add support for nested HTTP callouts.

---

.github/workflows/rust.yml
WORKSPACE
bazel/dependencies.bzl
bazel/repositories.bzl

Cleanup WORKSPACE.

---

Cargo.toml
bazel/cargo/Cargo.lock
bazel/cargo/crates.bzl
bazel/cargo/remote/BUILD.chrono-0.4.19.bazel
bazel/cargo/remote/BUILD.getrandom-0.2.0.bazel
bazel/cargo/remote/BUILD.libc-0.2.81.bazel
bazel/cargo/remote/BUILD.time-0.1.44.bazel

Update libc (transitive dependency) to v0.2.81.

---

bazel/cargo/Cargo.raze.lock
bazel/cargo/crates.bzl
bazel/cargo/remote/BUILD.chrono-0.4.19.bazel
bazel/cargo/remote/BUILD.getrandom-0.2.2.bazel
bazel/cargo/remote/BUILD.libc-0.2.86.bazel
bazel/cargo/remote/BUILD.time-0.1.43.bazel

Update libc (transitive dependency) to v0.2.86.

---

bazel/cargo/Cargo.raze.lock
bazel/cargo/crates.bzl
bazel/cargo/remote/BUILD.chrono-0.4.19.bazel
bazel/cargo/remote/BUILD.getrandom-0.2.2.bazel
bazel/cargo/remote/BUILD.libc-0.2.87.bazel
bazel/cargo/remote/BUILD.time-0.1.43.bazel

Update libc (transitive dependency) to v0.2.87.

---

bazel/cargo/Cargo.raze.lock
bazel/cargo/crates.bzl
bazel/cargo/remote/BUILD.chrono-0.4.19.bazel
bazel/cargo/remote/BUILD.getrandom-0.2.2.bazel
bazel/cargo/remote/BUILD.libc-0.2.88.bazel
bazel/cargo/remote/BUILD.time-0.1.43.bazel

Update libc (transitive dependency) to v0.2.88.

---

Cargo.toml
bazel/cargo/BUILD.bazel
bazel/cargo/Cargo.raze.lock
bazel/cargo/crates.bzl
bazel/cargo/remote/BUILD.ahash-0.7.2.bazel
bazel/cargo/remote/BUILD.hashbrown-0.11.0.bazel
bazel/cargo/remote/BUILD.once_cell-1.7.2.bazel
bazel/cargo/remote/BUILD.version_check-0.9.2.bazel

Update hashbrown to v0.11.0.

---

bazel/cargo/Cargo.raze.lock
bazel/cargo/crates.bzl
bazel/cargo/remote/BUILD.chrono-0.4.19.bazel
bazel/cargo/remote/BUILD.getrandom-0.2.2.bazel
bazel/cargo/remote/BUILD.libc-0.2.89.bazel
bazel/cargo/remote/BUILD.time-0.1.43.bazel

Update libc (transitive dependency) to v0.2.89.

---

bazel/cargo/Cargo.raze.lock
bazel/cargo/crates.bzl
bazel/cargo/remote/BUILD.ahash-0.7.2.bazel
bazel/cargo/remote/BUILD.version_check-0.9.3.bazel

Update version_check (transitive dependency) to v0.9.3.

---

src/hostcalls.rs
src/traits.rs

Found by clippy's needless_borrow check.

Avoid unnecessary borrowing.

---

CHANGELOG.md
Cargo.toml
bazel/cargo/Cargo.raze.lock

Release v0.1.4.

---

README.md
WORKSPACE
bazel/cargo/BUILD.bazel
bazel/cargo/Cargo.raze.lock
bazel/cargo/crates.bzl
bazel/cargo/remote/BUILD.ahash-0.7.6.bazel
bazel/cargo/remote/BUILD.autocfg-1.0.1.bazel
bazel/cargo/remote/BUILD.cfg-if-1.0.0.bazel
bazel/cargo/remote/BUILD.chrono-0.4.19.bazel
bazel/cargo/remote/BUILD.getrandom-0.2.4.bazel
bazel/cargo/remote/BUILD.hashbrown-0.11.2.bazel
bazel/cargo/remote/BUILD.libc-0.2.116.bazel
bazel/cargo/remote/BUILD.log-0.4.14.bazel
bazel/cargo/remote/BUILD.num-integer-0.1.44.bazel
bazel/cargo/remote/BUILD.num-traits-0.2.14.bazel
bazel/cargo/remote/BUILD.once_cell-1.9.0.bazel
bazel/cargo/remote/BUILD.time-0.1.43.bazel
bazel/cargo/remote/BUILD.version_check-0.9.4.bazel
bazel/cargo/remote/BUILD.wasi-0.10.2+wasi-snapshot-preview1.bazel
bazel/cargo/remote/BUILD.winapi-0.3.9.bazel
bazel/cargo/remote/BUILD.winapi-i686-pc-windows-gnu-0.4.0.bazel
bazel/cargo/remote/BUILD.winapi-x86_64-pc-windows-gnu-0.4.0.bazel

Update cargo-raze to v0.14.1.

---

.github/workflows/rust.yml
Cargo.toml

Strip "debuginfo" by default.

---

BUILD
bazel/BUILD
examples/BUILD

Add license headers to BUILD files.

---

bazel/repositories.bzl
bazel/rules_rust.patch

Update rules_rust to v0.5.0 (with Rust v1.61.0).

---

Cargo.toml
bazel/cargo/BUILD.bazel
bazel/cargo/crates.bzl
bazel/cargo/remote/BUILD.ahash-0.8.2.bazel
bazel/cargo/remote/BUILD.hashbrown-0.13.1.bazel
bazel/cargo/remote/BUILD.once_cell-1.16.0.bazel

Update hashbrown to v0.13.

---

CHANGELOG.md
Cargo.toml
bazel/cargo/Cargo.raze.lock

Release v0.2.1.

---

.github/workflows/rust.yml
bazel/cargo/remote/defs.bzl

Ran the CI command to fix up cargo/remote/defs.bzl:
```
$ bazelisk --noworkspace_rc run --noenable_bzlmod //bazel/cargo:crates_vendor
```

Regenerate Bazel artifacts.

---

Cargo.toml
bazel/cargo/Cargo.Bazel.lock
bazel/cargo/remote/BUILD.bazel

Found with cargo publish (nightly).

Update version to v0.2.3-dev.
