proxy-wasm/proxy-wasm-rust-sdk

- CHANGELOG.md
- Cargo.toml
- cargo/Cargo.lock
> Release v0.1.1.

- .github/workflows/rust.yml
While there, align style with the test framework.
> Move optional checks to the end.

- examples/http_body.rs
> Fix HTTP body example.

- src/hostcalls.rs
- src/types.rs
> Add metrics.

- Cargo.toml
- bazel/cargo/BUILD
- bazel/cargo/Cargo.lock
- bazel/cargo/crates.bzl
- bazel/cargo/remote/ahash-0.4.6.BUILD
- bazel/cargo/remote/autocfg-1.0.1.BUILD
- bazel/cargo/remote/chrono-0.4.19.BUILD
- bazel/cargo/remote/hashbrown-0.9.1.BUILD
- bazel/cargo/remote/libc-0.2.80.BUILD
- bazel/cargo/remote/num-integer-0.1.44.BUILD
- bazel/cargo/remote/num-traits-0.2.14.BUILD
- bazel/cargo/remote/time-0.1.44.BUILD
- bazel/cargo/remote/wasi-0.10.0+wasi-snapshot-preview1.BUILD
> Update hashbrown and transitive dependencies.

- .github/workflows/rust.yml
- src/allocator.rs
> Allow building for wasm32-wasi target.

- examples/http_body.rs
> Fix warnings from Clippy v1.50.0 (nightly).

- CHANGELOG.md
- Cargo.toml
- bazel/cargo/Cargo.lock
> Release v0.1.3.

- README.md
> Cleanup instructions for updating dependencies.

- examples/BUILD
- examples/http_body.rs
- examples/http_config.rs
- examples/http_headers.rs
> Cleanup examples.

- .github/workflows/rust.yml
It was removed in #75, and while Cargo.raze.lock being outdated
was still caught as part of the cargo-raze format check, mixing
formatting and freshness checks resulted in confusing reporting.
> Restore freshness check for Cargo.raze.lock.

- .github/workflows/rust.yml
- Cargo.toml
- README.md
- WORKSPACE
- bazel/cargo/remote/BUILD.ahash-0.4.7.bazel
- bazel/cargo/remote/BUILD.autocfg-1.0.1.bazel
- bazel/cargo/remote/BUILD.cfg-if-1.0.0.bazel
- bazel/cargo/remote/BUILD.chrono-0.4.19.bazel
- bazel/cargo/remote/BUILD.getrandom-0.2.2.bazel
- bazel/cargo/remote/BUILD.hashbrown-0.9.1.bazel
- bazel/cargo/remote/BUILD.libc-0.2.88.bazel
- bazel/cargo/remote/BUILD.log-0.4.14.bazel
- bazel/cargo/remote/BUILD.num-integer-0.1.44.bazel
- bazel/cargo/remote/BUILD.num-traits-0.2.14.bazel
- bazel/cargo/remote/BUILD.time-0.1.43.bazel
- bazel/cargo/remote/BUILD.wasi-0.10.2+wasi-snapshot-preview1.bazel
- bazel/cargo/remote/BUILD.winapi-0.3.9.bazel
- bazel/cargo/remote/BUILD.winapi-i686-pc-windows-gnu-0.4.0.bazel
- bazel/cargo/remote/BUILD.winapi-x86_64-pc-windows-gnu-0.4.0.bazel
- bazel/dependencies.bzl
- bazel/repositories.bzl
While there, add support for generating BUILD files
with Bazel using @cargo_raze//:raze.
> Update cargo-raze to v0.11.0.

- bazel/cargo/Cargo.raze.lock
- bazel/cargo/crates.bzl
- bazel/cargo/remote/BUILD.chrono-0.4.19.bazel
- bazel/cargo/remote/BUILD.getrandom-0.2.2.bazel
- bazel/cargo/remote/BUILD.libc-0.2.90.bazel
- bazel/cargo/remote/BUILD.time-0.1.43.bazel
> Update libc (transitive dependency) to v0.2.90.

- bazel/cargo/BUILD.bazel
- bazel/cargo/Cargo.raze.lock
- bazel/cargo/crates.bzl
- bazel/cargo/remote/BUILD.hashbrown-0.11.1.bazel
> Update hashbrown to v0.11.1.

- .github/workflows/rust.yml
> Remove freshness check for Cargo.raze.lock.

- src/dispatcher.rs
- src/hostcalls.rs
- src/traits.rs
- src/types.rs
Add gRPC stream support for Rust SDK. It includes any workaround around callout token table caused by #100 is not landed to master.
> Add support for gRPC streams.

- src/hostcalls.rs
- src/traits.rs
While there, unify style and unwrap errors in gRPC traits.
> Add missing hostcalls for gRPC and HTTP callouts.

- src/hostcalls.rs
- src/traits.rs
> Add hostcalls for maps that use bytes instead of UTF-8 strings.

- .github/workflows/rust.yml
Fixes issues with addlicense requiring Go v1.16+.
> Use actions/setup-go@v2 in GitHub Actions.

- BUILD
- bazel/repositories.bzl
- examples/BUILD
This will likely require the lockfiles to be regenerated to update `edition` versions, but to prevent conflicts it's better to do this after https://github.com/proxy-wasm/proxy-wasm-rust-sdk/pull/131 has been merged.
Extracted from: #129
> Update rules_rust to latest (with Rust v1.58.1).

- CHANGELOG.md
- Cargo.toml
- bazel/cargo/Cargo.raze.lock
> Release v0.2.0.

- .github/workflows/rust.yml
- CHANGELOG.md
- Cargo.toml
- bazel/cargo/Cargo.raze.lock
- src/allocator.rs
The "wee_alloc" crate is no longer maintained and it leaks memory.
Reported in #167.
> Remove "wee-alloc" feature.

- src/dispatcher.rs
Fixes #153. 
This PR:
* Logs in `on_grpc_close` when an invalid `token_id` is sent from the host. This happens in Envoy when the initial connection fails.
> Don't panic on unknown token_id in on_grpc_close.

- examples/http_body/src/lib.rs
> Fix uninlined-format-args warning from clippy nightly.

- src/dispatcher.rs
Sometimes `Dispatcher.on_grpc_receive_initial_metadata()` will get an invalid stream ID, and then panic. `Dispatcher.on_grpc_receive_trailing_metadata()` as well.
This is a quick fix that will turn a `panic!()` call into a `trace!()` call. The broader issue/bug is out of scope here, though as far as I know it's benign other than this panic.
~NOTE: there may be a more concise way to write this Rust code.~ (thanks Piotr)
NOTE: adding this change to `on_grpc_receive()` as well, just to be safe, even though I haven't seen this panic get triggered myself.
See:
1. Issue with more details: https://github.com/proxy-wasm/proxy-wasm-rust-sdk/issues/206
2. Issue tracking why these two methods get an invalid token number at all: https://github.com/proxy-wasm/proxy-wasm-cpp-host/issues/373
> Don't panic on unknown token_id in gRPC callbacks.

- BUILD
Bazel examples were removed in #146.
> Restore Bazel example to verify working rules_rust.

- src/hostcalls.rs
- src/types.rs
Adds the missing `Status` enum variants...
We currently run into `SerializationFailure` when getting some attribute `filter_state` from Envoy... Today, this not only panics, but the error isn't even really recognized. 
I'm not sure, given the current `trait Context` definition how to best deal with these gracefully tho? The default implementation are "just" `Result::unwrap()` ing the underlying host call.. So thinking that [this](https://github.com/proxy-wasm/proxy-wasm-rust-sdk/pull/237/commits/64712b3d50dd0eb45db8de2af6be9e31bfb83ff2) is the best for now, wdyt?
> Accept more Status codes in get_property.

- src/hostcalls.rs
> Accept more Status codes in call_foreign_function.

- src/dispatcher.rs
Panic with message "proxy-wasm-rust-sdk/src/dispatcher.rs:121:14:\nalready borrowed: BorrowMutError" is triggered when `dispatch_grpc_call()` is invoked from `on_grpc_call_response()`. The problem is originated by a [`self.grpc_callouts.borrow_mut()` being invoked inside an `if` condition](https://github.com/proxy-wasm/proxy-wasm-rust-sdk/blob/main/src/dispatcher.rs#L456), that keeps the `RefMut` alive until the `true` branch ends. 
This PR adopts the [same approach than on_http_call_response()](https://github.com/proxy-wasm/proxy-wasm-rust-sdk/blob/main/src/dispatcher.rs#L409), by invoking the `RefCell::borrow_mut()` outside the `if` condition.
> Add support for nested gRPC callouts.

- .github/workflows/rust.yml
- README.md
- examples/grpc_auth_random/Cargo.toml
- examples/grpc_auth_random/README.md
- examples/grpc_auth_random/docker-compose.yaml
- examples/grpc_auth_random/envoy.yaml
- examples/grpc_auth_random/src/lib.rs
- src/hostcalls.rs
- src/traits.rs
- src/types.rs
Note that some hosts (e.g. Envoy v1.31+) already map HTTP status codes
from send_http_response() to gRPC status codes, when talking with gRPC
clients, so this API is needed only when more control is needed.
Fixes #148.
> Add support for sending error responses with gRPC status codes.

- .github/workflows/rust.yml
- examples/grpc_auth_random/docker-compose.yaml
- examples/hello_world/docker-compose.yaml
- examples/http_auth_random/docker-compose.yaml
- examples/http_body/docker-compose.yaml
- examples/http_config/docker-compose.yaml
- examples/http_headers/docker-compose.yaml
Notably, it fixes an issue with always injecting invalid "grpc-status"
HTTP response header when sending local HTTP response to gRPC clients.
Fixes #211.
> Update Envoy to v1.31.

- .github/workflows/rust.yml
- Cargo.toml
Technically, this happened as a result of hashbrown update in #195,
but we didn't catch it at the time.
Add tests using MSRV to prevent this from happening in the future.
> Update MSRV to Rust v1.64.0.

- src/hostcalls.rs
Before:
utils::bench_deserialize_map       ... bench:   171.39 ns/iter (+/- 3.53)
utils::bench_deserialize_map_bytes ... bench:   148.27 ns/iter (+/- 3.19)
After:
utils::bench_deserialize_map       ... bench:   168.34 ns/iter (+/- 3.19)
utils::bench_deserialize_map_bytes ... bench:   145.40 ns/iter (+/- 1.92)
> Optimize Vec allocations in map deserialization.

- .github/workflows/rust.yml
- Cargo.toml
Hashbrown updated its MSRV in a patch release (v0.15.1),
so we have to follow.
> Update MSRV to Rust v1.65.0.

- .github/workflows/rust.yml
While there, re-enable cargo audit now that it supports Cargo lockfile v4.
> Use cargo outdated fork to workaround its outdated dependencies.

- bazel/cargo/Cargo.Bazel.lock
- bazel/cargo/remote/BUILD.allocator-api2-0.2.21.bazel
- bazel/cargo/remote/BUILD.bazel
- bazel/cargo/remote/BUILD.foldhash-0.1.4.bazel
- bazel/cargo/remote/BUILD.hashbrown-0.15.2.bazel
- bazel/cargo/remote/defs.bzl
The RUSTSEC-2024-0402 advisory was published for a feature of hashbrown
that we don't use, but we need to update its version in the lockfile to
silence the warning.
> Update hashbrown to v0.15.2.

- src/allocator.rs
`#[export_name]` already takes precedence over `#[no_mangle]`,
so this is a no-op, but it silences the warning.
Found with nightly.
> Fix conditional attributes in exported allocator name.

- examples/envoy_filter_metadata/src/lib.rs
> Fix formatting in Envoy metadata example.

- src/hostcalls.rs
The method `get_http_request_headers_bytes` return empty vector for empty header value but `get_http_request_header_bytes` returns None for empty header value.   
Similarly `get_http_request_headers` returns empty String but `get_http_request_header` returns None.
This commit intends to fix this inconsistency.
With this, it will be possible to differentiate between two cases, a missing header and a header with empty value.
> Differentiate between missing and empty headers.

- src/hostcalls.rs
Before:
utils::bench_serialize_map         ... bench:    66.87 ns/iter (+/- 1.33)
utils::bench_serialize_map_bytes   ... bench:    69.42 ns/iter (+/- 1.45)
After:
utils::bench_serialize_map         ... bench:    55.84 ns/iter (+/- 1.16)
utils::bench_serialize_map_bytes   ... bench:    56.03 ns/iter (+/- 1.19)
Note that this is changed only in the private functions to avoid breaking
the public API.
> Pass slice instead of Vec during map serialization.

- examples/grpc_auth_random/src/lib.rs
- examples/http_auth_random/src/lib.rs
unsigned_is_multiple_of() was stabilized very recently, and while
the suggested code might be more idiomatic, it's not supported by
our MSRV or even the stable version currently used in rules_rust.
> Ignore clippy's manual_is_multiple_of warning.
